/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ChessGame;
import ChessGame.ChessGUI;
public class App {

    public static void main(String[] args) {
        ChessGUI chess = new ChessGUI();
    }
}
