/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ChessGame;
import ChessGame.*;
public class App {

    public static void main(String[] args) {
        ChessBoard chessBoard = new ChessBoard();
        ChessController myController = new ChessController(chessBoard);
    }
}
